drop table COURSE_SESSION;

drop table CLIENT;

drop table COURSE;

drop table LOCATION;

create table COURSE_SESSION
(
     ID_SESSION DB_INTEGER(3) not null ,
     ID DB_INTEGER(3) not null ,
     CODE DB_TEXT, 255 not null ,
     START_DATE DB_DATE(8) not null ,
     END_DATE DB_DATE(8) not null ,
     MAX DB_INTEGER(5) null
,   CONSTRAINT PK_COURSE_SESSION PRIMARY KEY (ID_SESSION)
);

create table CLIENT
(
     ID_CLIENT DB_INTEGER(3) not null ,
     ID_SESSION DB_INTEGER(3) not null ,
     LASTNAME DB_TEXT, 255 not null ,
     FIRSTNAME DB_TEXT, 255 not null ,
     ADDRESS DB_TEXT, 255 not null ,
     PHONE DB_TEXT, 255 not null ,
     EMAIL DB_TEXT, 255 not null
,   CONSTRAINT PK_CLIENT PRIMARY KEY (ID_CLIENT)
);

create table COURSE
(
     CODE DB_TEXT, 255 not null ,
     TITLE DB_TEXT, 255 not null
,   CONSTRAINT PK_COURSE PRIMARY KEY (CODE)
);

create table LOCATION
(
     ID DB_INTEGER(3) not null ,
     CITY DB_TEXT, 255 not null
,   CONSTRAINT PK_LOCATION PRIMARY KEY (ID)
);

ALTER TABLE COURSE_SESSION ADD
     CONSTRAINT FK_COURSE_SESSION_LOCATION
          FOREIGN KEY (ID)
               REFERENCES LOCATION (ID)

ALTER TABLE COURSE_SESSION ADD
     CONSTRAINT FK_COURSE_SESSION_COURSE
          FOREIGN KEY (CODE)
               REFERENCES COURSE (CODE)

ALTER TABLE CLIENT ADD
     CONSTRAINT FK_CLIENT_COURSE_SESSION
          FOREIGN KEY (ID_SESSION)
               REFERENCES COURSE_SESSION (ID_SESSION)